[package]
name = "retros"
version = "0.1.0"
authors = ["Gui Gessele <guilherme@serel.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
